baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "borland"
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
   name = "Neural Network Architectures"
   url = "/nna/"
   weight = 1
  [[menu.main]]
   name = "Basic Architectures"
   parent = "Neural Network Architectures"
   url = "/nna/ba"
   weight = 1
  [[menu.main]]
   name = "Multi-layer Perceptron"
   parent = "Basic Architectures"
   url = "/nna/ba/mlp/"
   weight = 1
  [[menu.main]]
   name = "Convolutional Neural Networks"
   parent = "Basic Architectures"
   url = "/nna/ba/cnn/"
   weight = 2
  [[menu.main]]
   name = "Recurrent Networks"
   parent = "Neural Network Architectures"
   url = "/rnn/"
   weight = 2
  [[menu.main]]
   name = "Vanilla"
   url = "/nna/rnn/vanilla"
   parent = "Recurrent Networks"
   weight = 2
  [[menu.main]]
   name = "Bidirectional"
   url = "/nna/rnn/brnns"
   parent = "Recurrent Networks"
   weight = 2
  [[menu.main]]
   name = "LSTM"
   url = "/nna/rnn/lstm"
   parent = "Recurrent Networks"
   weight = 3
  [[menu.main]]
   name = "GRU"
   url = "/nna/rnn/gru"
   parent = "Recurrent Networks"
   weight = 4
  [[menu.main]]
   name = "xLSTM"
   url = "/nna/rnn/xlstm"
   parent = "Recurrent Networks"
   weight = 4
  [[menu.main]]
   name = "Transformers"
   parent = "Neural Network Architectures"
   url = "/nna/transformers/"
   weight = 2
  [[menu.main]]
   name = "Vanilla"
   url = "/nna/transformers/vanilla"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Linear"
   url = "/nna/transformers/linear"
   parent = "Transformers"
   weight = 1
  [[menu.main]]
   name = "Sparse"
   url = "/nna/transformers/sparse"
   parent = "Transformers"
   weight = 1
  [[menu.main]]
   name = "Gaussian"
   url = "/nna/transformers/gaussian"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Differential"
   url = "/nna/transformers/differential"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Universal"
   url = "/nna/transformers/universal"
   parent = "Transformers"
   weight = 2
  

