baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "borland"
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
   name = "Multi-layer Perceptron"
   url = "/mlp/"
   weight = 1
  [[menu.main]]
   name = "Convolutional Neural Networks"
   url = "/cnn/"
   weight = 2
  [[menu.main]]
   name = "Recurrent Neural Networks"
   url = "/rnn/"
   weight = 2
  [[menu.main]]
   name = "Vanilla"
   url = "/rnn/vanilla"
   parent = "Recurrent Neural Networks"
   weight = 2
  [[menu.main]]
   name = "Bidirectional"
   url = "/rnn/brnns"
   parent = "Recurrent Neural Networks"
   weight = 2
  [[menu.main]]
   name = "LSTM"
   url = "/rnn/lstm"
   parent = "Recurrent Neural Networks"
   weight = 3
  [[menu.main]]
   name = "GRU"
   url = "/rnn/gru"
   parent = "Recurrent Neural Networks"
   weight = 4
  [[menu.main]]
   name = "xLSTM"
   url = "/rnn/xlstm"
   parent = "Recurrent Neural Networks"
   weight = 4
  [[menu.main]]
   name = "Transformers"
   url = "/transformers/"
   weight = 2
  [[menu.main]]
   name = "Vanilla"
   url = "/transformers/vanilla"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Linear"
   url = "/transformers/linear"
   parent = "Transformers"
   weight = 1
  [[menu.main]]
   name = "Sparse"
   url = "/transformers/sparse"
   parent = "Transformers"
   weight = 1
  [[menu.main]]
   name = "Gaussian"
   url = "/transformers/gaussian"
   parent = "Transformers"
   weight = 2

