baseURL = '/'
languageCode = 'en-us'
title = 'The CookBook'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "borland"
    tabWidth = 4

[params]
  math = true

[minify]
  disableHTML = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
   name = "Neural Network Architectures"
   url = "/nna/"
   weight = 1
  [[menu.main]]
   name = "Rienforcement Learning"
   url = "/rl/"
   weight = 1
  [[menu.main]]
   name = "Policy Gradient Methods"
   parent = "Rienforcement Learning"
   url = "/rl/pgm/"
  [[menu.main]]
   name = "Value Based Methods"
   parent = "Rienforcement Learning"
   url = "/rl/vbm/"
  [[menu.main]]
   name = "Deep Q networks"
   parent = "Value Based Methods"
   url = "/rl/vbm/dqn/"
  [[menu.main]]
   name = "PPO"
   parent = "Policy Gradient Methods"
   url = "/rl/pgm/ppo/"
   weight = 1
  [[menu.main]]
   name = "Basic Architectures"
   parent = "Neural Network Architectures"
   url = "/nna/ba"
   weight = 1
  [[menu.main]]
   name = "ResNet"
   parent = "Basic Architectures"
   url = "/nna/ba/resnet/"
   weight = 1
  [[menu.main]]
   name = "DenseNet"
   parent = "Basic Architectures"
   url = "/nna/ba/densenet/"
   weight = 1
  [[menu.main]]
   name = "Multi-layer Perceptron"
   parent = "Basic Architectures"
   url = "/nna/ba/mlp/"
   weight = 1
   [[menu.main]]
   name = "Memory Networks"
   parent = "Basic Architectures"
   url = "/nna/ba/memn/"
   weight = 1
  [[menu.main]]
   name = "Convolutional Neural Networks"
   parent = "Basic Architectures"
   url = "/nna/ba/cnn/"
   weight = 2
  [[menu.main]]
   name = "Recurrent Networks"
   parent = "Neural Network Architectures"
   url = "/rnn/"
   weight = 2
  [[menu.main]]
   name = "Vanilla Recurrent"
   url = "/nna/rnn/vanilla"
   parent = "Recurrent Networks"
   weight = 3
  [[menu.main]]
   name = "Bidirectional"
   url = "/nna/rnn/brnns"
   parent = "Recurrent Networks"
   weight = 2
  [[menu.main]]
   name = "LSTM"
   url = "/nna/rnn/lstm"
   parent = "Recurrent Networks"
   weight = 3
  [[menu.main]]
   name = "GRU"
   url = "/nna/rnn/gru"
   parent = "Recurrent Networks"
   weight = 4
  [[menu.main]]
   name = "xLSTM"
   url = "/nna/rnn/xlstm"
   parent = "Recurrent Networks"
   weight = 4
  [[menu.main]]
   name = "Auto-Encoders"
   parent = "Neural Network Architectures"
   url = "/nna/autoencoders/"
   weight = 2
  [[menu.main]]
   name = "Variational"
   parent = "Auto-Encoders"
   url = "/nna/autoencoders/variational"
   weight = 2
  [[menu.main]]
   name = "VQ-VAE"
   parent = "Auto-Encoders"
   url = "/nna/autoencoders/vqvae"
   weight = 2
  [[menu.main]]
   name = "Contractive "
   parent = "Auto-Encoders"
   url = "/nna/autoencoders/contractive"
   weight = 2
  [[menu.main]]
   name = "Sparse "
   parent = "Auto-Encoders"
   url = "/nna/autoencoders/sparse"
   weight = 2
  [[menu.main]]
   name = "Diffusion Models"
   parent = "Neural Network Architectures"
   url = "/nna/diffusion/"
   weight = 2
  [[menu.main]]
   name = "DDPM"
   url = "/nna/diffusion/ddpm"
   parent = "Diffusion Models"
   weight = 2
  [[menu.main]]
   name = "DDIM"
   url = "/nna/diffusion/ddim"
   parent = "Diffusion Models"
   weight = 2
  [[menu.main]]
   name = "Transformers"
   parent = "Neural Network Architectures"
   url = "/nna/transformers/"
   weight = 2
  [[menu.main]]
   name = "Vanilla Transformer"
   url = "/nna/transformers/vanilla"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Transformers^2"
   url = "/nna/transformers/transformers2"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Negative"
   url = "/nna/transformers/negative"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Titan"
   url = "/nna/transformers/titan"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Byte Latent"
   url = "/nna/transformers/blt"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Atlas"
   url = "/nna/transformers/atlas"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Linear"
   url = "/nna/transformers/linear"
   parent = "Transformers"
   weight = 1
  [[menu.main]]
   name = "Sparse"
   url = "/nna/transformers/sparse"
   parent = "Transformers"
   weight = 1
  [[menu.main]]
   name = "Gaussian"
   url = "/nna/transformers/gaussian"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Differential"
   url = "/nna/transformers/differential"
   parent = "Transformers"
   weight = 2
  [[menu.main]]
   name = "Universal"
   url = "/nna/transformers/universal"
   parent = "Transformers"
   weight = 2
  

